config/routes.rb
Cashflow::Application.routes.draw do
  resources :budget_posts

  devise_for :users,
             class_name: "Person",
             controllers: { omniauth_callbacks: "people/omniauth_callbacks" }
  devise_scope :user do
    get "sign_in",
        to: "people/omniauth_callbacks#new",
        as: :new_session
    delete "sign_out",
           to: "people/omniauth_callbacks#destroy",
           as: :destroy_user_session
  end

  localized(["sv"]) do
    resources :product_types
    resources :budget, except: [:destroy] do
      resources :budget_rows, as: "rows", only: [:index, :show, :edit, :update]
    end
    resources :budget_posts
    resources :business_units
    resources :purchases do
      collection do
        get :confirmed
        put :pay_multiple
      end
      member do
        put :confirm
        put :pay
        put :keep
        put :cancel
      end
    end

    resources :people, except: [:destroy] do
      collection do
        get :search
      end
    end

    root to: "dashboard#index"
  end
end

app/controllers/product_types_controller.rb
class ProductTypesController < ApplicationController
  load_and_authorize_resource
  before_filter :get_items, only: [:show, :edit, :update, :destroy]

  def index
    @product_types = ProductType.all
  end

  def show
  end

  def new
    @product_type = ProductType.new
  end

  def edit
  end

  def create
    @product_type = ProductType.new(params[:product_type])

    if @product_type.save
      redirect_to(@product_type,
                  notice: I18n.t("notices.product_type.success.created"))
    else
      render action: "new"
    end
  end

  def update
    if @product_type.update_attributes(params[:product_type])
      redirect_to(@product_type,
                  notice: I18n.t("notices.product_type.success.updated"))
    else
      render action: "edit"
    end
  end

  def destroy
    unless @product_type.destroy
      flash[:error] =
        I18n.t("activerecord.errors.models.product_type.cannot_be_removed")
    end

    redirect_to(product_types_url)
  end

  protected

  def get_items
    @items = [{ key: :show_product_type,
                name: @product_type.name,
                url: product_type_path(@product_type) },
              { key: :edit_product_type,
                name: I18n.t("edit"),
                url: edit_product_type_path(@product_type) }
             ]
  end
end

app/views/product_types/_form.html.haml
= semantic_form_for(@product_type) do |form|
 = form.inputs :name => "Attribut" do
  = form.input :name
  = form.input :description
  = form.input :mage_account_number,
               as: :select,
               collection: Mage::Account.all.map { |a| ["#{a.number}-#{a.name}", a.number] }
   = form.actions do
  = form.action :submit, as: :button

app/views/product_types/index.html.haml
%h2= t('.title')

%table.table.table-striped
  %thead
    %tr
      %th= t 'activerecord.attributes.product_type.name'
      %th= t 'activerecord.attributes.product_type.description'
      - if can?(:manage, ProductType)
        %th.actions
  %tbody
    - for product_type in @product_types
      %tr
        %td= link_to product_type, product_type
        %td= product_type.description
        - if can?(:manage, ProductType)
          %td
            = link_to edit_product_type_path(product_type), class: 'btn' do
              %i.glyphicon.glyphicon-pencil
              = t('edit')
            = link_to product_type, confirm: t('are_you_sure'), method: :delete, class: 'btn btn-danger' do
              %i.glyphicon.glyphicon-trash
              = t('destroy')

.well
  = link_to new_product_type_path, class: 'btn btn-info' do
    %i.glyphicon.glyphicon-file
    Ny produkttyp

app/views/product_types/show.html.haml
%h1= @product_type

%article
  %p= @product_type.description