config/routes.rb
Cashflow::Application.routes.draw do
  resources :budget_posts

  devise_for :users,
             class_name: "Person",
             controllers: { omniauth_callbacks: "people/omniauth_callbacks" }
  devise_scope :user do
    get "sign_in",
        to: "people/omniauth_callbacks#new",
        as: :new_session
    delete "sign_out",
           to: "people/omniauth_callbacks#destroy",
           as: :destroy_user_session
  end

  localized(["sv"]) do
    resources :product_types
    resources :budget, except: [:destroy] do
      resources :budget_rows, as: "rows", only: [:index, :show, :edit, :update]
    end
    resources :budget_posts
    resources :business_units
    resources :purchases do
      collection do
        get :confirmed
        put :pay_multiple
      end
      member do
        put :confirm
        put :pay
        put :keep
        put :cancel
      end
    end

    resources :people, except: [:destroy] do
      collection do
        get :search
      end
    end

    root to: "dashboard#index"
  end
end

app/models/budget_post.rb
class BudgetPost < ActiveRecord::Base
  has_many :purchases, dependent: :restrict_with_exception
  has_many :budget_rows, -> { order 'year desc' }, dependent: :destroy
  belongs_to :business_unit

  validates :mage_arrangement_number, presence: true

  after_create :create_rows

  default_scope -> { order('name ASC') }

  def to_s
    name
  end

  # return an array of all years for which there are any budget rows
  def self.all_years
    [Time.now.year] | BudgetRow.group(:year).select(:year).order('year desc').map(&:year)
  end

  def row(year)
    budget_rows.find_by_year(year)
  end

  protected

  def create_rows
    BudgetPost.all_years.each do |y|
      BudgetRow.create(budget_post: self, year: y)
    end
  end
end

app/controllers/budget_posts_controller.rb
class BudgetPostsController < ApplicationController
  load_and_authorize_resource

  def index
    @budget_posts = BudgetPost.all
    @year = params[:year]
    @year = Time.now.year if @year.nil?

    # TODO: Refactor this to put it elsewhere. It doesn't belong here.
    BudgetRow.create_rows_if_not_exists(@year)

    @edit = params[:edit]
  end

  def show
  end

  def new
    @budget_post = BudgetPost.new
    @budget_post.mage_arrangement_number = 0 # THIS IS A HACK
  end

  def edit
  end

  def create
    @budget_post = BudgetPost.new(budget_post_params)

    if @budget_post.save
      redirect_to(@budget_post,
                  notice: I18n.t("notices.budget_post.success.created"))
    else
      render action: "new"
    end
  end

  def update
    if @budget_post.update_attributes(params[:budget_post])
      redirect_to(budget_post_path(@budget_post),
                  notice: I18n.t("notices.budget_post.success.updated"))
    else
      render action: "edit"
    end
  end

  def destroy
    @budget_post = BudgetPost.find(params[:id])
    begin
      @budget_post.destroy
      notice = I18n.t("notices.budget_post.success.delete")
    rescue ActiveRecord::DeleteRestrictionError => _e
      notice = I18n.t("notices.budget_post.error.delete_restricted")
    end

    redirect_to(budget_posts_url, notice: notice)
  end

  protected

  def budget_post_params
    params.require(:budget_post).permit(:business_unit_id,
                                        :name,
                                        :mage_arrangement_number)
  end
end

app/views/budget_posts/_form.html.haml
= semantic_form_for(@budget_post) do |form|
  = form.inputs name: 'Attribut' do
    = form.input :name
    = form.input :business_unit
    - unless @budget_post.business_unit.nil? # THIS SHOULD NEVER BE
      = form.input :mage_arrangement_number,
                   as: :select,
                   collection: Mage::Arrangement.all(@budget_post.business_unit.mage_number).map { |a| [a.name, a.number] }
    - else
      = form.input :mage_arrangement_number, as: :hidden
  = form.actions do
    = form.action :submit, as: :button

app/views/budget_posts/edit.html.haml
%h1= t '.title'
= render :partial=>"form"

app/views/budget_posts/index.html.haml
%div
  = form_tag '',:id=>:year_select_form,:method=>:get do
    = label_tag :year, t('show_budget_rows_for')
    = select_tag(:year, options_from_collection_for_select(BudgetPost.all_years, :to_i, :to_s, @year))

%h2= t('.title')

%table.table.table-striped
  %thead
    %tr
      %th= t 'activerecord.attributes.budget_post.name'
      %th= t 'activerecord.models.business_unit'
      - if can?(:manage, BudgetPost)
        %th.actions

  %tbody
    - for budget_post in @budget_posts
      %tr{ :class => cycle(:odd, :even) }
        %td= link_to budget_post.name, budget_post
        %td= link_to budget_post.business_unit, budget_post.business_unit
        - if can?(:manage, BudgetPost)
          %td
            = link_to edit_budget_post_path(budget_post), class: 'btn' do
              %i.glyphicon.glyphicon-pencil
              = t('edit')
            = link_to budget_post, confirm: t('are_you_sure'), method: :delete, class: 'btn btn-danger' do
              %i.glyphicon.glyphicon-trash
              = t('destroy')

.well
  = link_to new_budget_post_path, class: 'btn btn-info' do
    %i.glyphicon.glyphicon-file
    Ny budgetpost

:javascript
  $("#save_budget").submit(function() {
    $("#set_budget").submit()
    return false
  })

app/views/budget_posts/new.html.haml
%h1= t '.title'
= render :partial=>'form'

app/views/budget_posts/show.html.haml
%h1= @budget_post.name

%article
  %p #{t('activerecord.models.business_unit')}: #{@budget_post.business_unit}

  %h2 Historik
  %table.table.table-striped
    %thead
      %tr
        %th= t 'activerecord.attributes.budget_row.year'
        %th= t 'activerecord.attributes.budget_post.budget'
        %th= t 'activerecord.attributes.budget_post.used'
        %th
    %tbody
      - @budget_post.budget_rows.each do |row|
        %tr
          %td= row.year
          %td= row.sum
          %td= row.total
          %td
            %progress{ min: 0, max: row.sum, value: row.total, style: "vertical-align: middle"}