config/routes.rb
Cashflow::Application.routes.draw do
  resources :budget_posts

  devise_for :users,
             class_name: "Person",
             controllers: { omniauth_callbacks: "people/omniauth_callbacks" }
  devise_scope :user do
    get "sign_in",
        to: "people/omniauth_callbacks#new",
        as: :new_session
    delete "sign_out",
           to: "people/omniauth_callbacks#destroy",
           as: :destroy_user_session
  end

  localized(["sv"]) do
    resources :product_types
    resources :budget, except: [:destroy] do
      resources :budget_rows, as: "rows", only: [:index, :show, :edit, :update]
    end
    resources :budget_posts
    resources :business_units
    resources :purchases do
      collection do
        get :confirmed
        put :pay_multiple
      end
      member do
        put :confirm
        put :pay
        put :keep
        put :cancel
      end
    end

    resources :people, except: [:destroy] do
      collection do
        get :search
      end
    end

    root to: "dashboard#index"
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  load_and_authorize_resource
  skip_load_resource only: [:create]
  before_filter :get_items, only: [:show, :edit, :update, :destroy]

  def index
    # Set pg_trgm similarity threshold a bit lower than the default (0.3) to be
    # able to match some partial words.
    # This lives here because the threshold is a per-connection thing.
    ActiveRecord::Base.connection.execute("select set_limit(0.2)")

    @purchases = Purchase
    search, filter = extract_filter_params
    @purchases = @purchases.fuzzy_search(search) unless search.blank?
    @purchases = filter.reduce(@purchases) { |query, f| query.where(f) }

    @purchases = @purchases.page(params.permit(:page)[:page])
  end

  def show
  end

  def new
    @purchase = current_user.purchases.new
    @purchase.items.build
  end

  def edit
  end

  def create
    @purchase = @current_user.purchases.new(purchase_params)

    if @purchase.person_id != current_user.id
      authorize! :edit, :purchase_owner
    end

    if @purchase.save
      Notifier.purchase_created(@purchase).deliver_now
      redirect_to(@purchase, notice: I18n.t("notices.purchase.success.created"))
    else
      render action: "new"
    end
  end

  def update
    @purchase.workflow_state = "edited"

    if @purchase.update_attributes(purchase_params)
      redirect_to(@purchase, notice: I18n.t("notices.purchase.success.updated"))
    else
      render action: "edit"
    end
  end

  def confirmed
    authorize! :manage, Purchase

    @purchases = Purchase.payable_grouped_by_person
  end

  def pay_multiple
    authorize! :manage, Purchase

    purchase_ids = Purchase.pay_multiple!(params).sort

    redirect_to(confirmed_purchases_path, notice: "Betalda (#{purchase_ids})!")
  end

  def confirm
    if @purchase.confirm!
      Notifier.purchase_approved(@purchase).deliver_now
    end
    redirect_to(purchase_path(@purchase))
  end

  def pay
    if @purchase.pay!
      Notifier.purchase_paid(@purchase).deliver_now
    end
    redirect_to(purchase_path(@purchase))
  end

  def keep
    authorize! :bookkeep, Purchase
    if @purchase.keep!
      voucher = Mage::Voucher.from_purchase(@purchase)
      unless voucher.push(@purchase.last_updated_by)
        fail "An error occured when pushing #{@purchase.inspect}\
        to MAGE (push returned false)".gsub(/\s+/, " ")
      end
    end
    redirect_to(purchase_path(@purchase))
  end

  def cancel
    if @purchase.cancel!
      Notifier.purchase_denied(@purchase).deliver_now
    end
    redirect_to(purchase_path(@purchase))
  end

  protected

  def purchase_params
    params.require(:purchase).permit(
      :person_id,
      :purchased_on,
      :budget_post_id,
      :description,
      :comment,
      :product_type_id,
      items_attributes: [:id,
                         :product_type_id,
                         :amount,
                         :comment,
                         :_destroy]
    )
  end

  def get_items
    @items = [{ key: :show_purchase_path,
                name: @purchase.slug,
                url: purchase_path(@purchase) }
             ]
    if @purchase.editable?
      @items << {
        key: :edit_purchase_path,
        name: I18n.t("edit"),
        url: edit_purchase_path(@purchase)
      }
    end
  end

  private

  def filter_params
    params.require(:filter).permit!
  end

  def extract_filter_params
    return "", [] if params[:filter].blank?

    hash = filter_params.clone
    arel = Purchase.arel_table
    search = hash.delete(:search)

    filter = %w[purchased_on updated_at].reduce([]) do |acc, attr|
      param = hash.delete("#{attr}_from")
      acc << arel[attr].gteq(param) unless param.blank?

      param = hash.delete("#{attr}_to")
      acc << arel[attr].lteq(param) unless param.blank?
      acc
    end

    filter << hash.reject { |_k, v| v.blank? }

    return search, filter
  end
end

app/helpers/purchases_helper.rb
# encoding: utf-8

module PurchasesHelper
  def budget_posts_for_purchase(purchase)
    purchase.budget_post.blank? ? nil : purchase.business_unit.budget_posts
  end

  def link_to_originator(version)
    if version.originator
      link_to(version.originator.name, person_path(version.originator))
    else
      ''
    end
  end

  def filter_search_tag(name, placeholder)
    options = { placeholder: placeholder }
    text_field_tag "filter[#{name}]", params[:filter].try(:[], name), options
  end

  def filter_select_tag(name, collection, value_method, text_method, options)
    filter = options_from_collection_for_select(collection,
                                                value_method,
                                                text_method,
                                                params[:filter].try(:[], name))
    select_tag "filter[#{name}]", filter, options
  end

  def filter_date_range_tags(name)
    content_tag :div, id: "purchase_#{name}_filter" do
      concat date_picker_tag("#{name}_from", "Från", "Välj ett startdatum")
      concat date_picker_tag("#{name}_to", "till och med", "Välj ett slutdatum")
    end
  end

  private

  def date_picker_tag(name, label, placeholder)
    capture do
      concat label_tag "filter[#{name}]", label
      concat text_field_tag("filter[#{name}]",
                            params[:filter].try(:[], name),
                            class: "datepicker",
                            placeholder: placeholder)
    end
  end
end

app/views/purchases/_filter_form.html.haml
%purchase_search
  = form_tag purchases_path, method: :get, class: "form form-inline" do
    = field_set_tag("Sök") do
      = filter_search_tag "search", "Sök i beskrivning..."
      = submit_tag "Sök!", id: "search_submit"

= content_tag :div, :id => "purchase_filter_toggle", :class => "btn" do
  %i.icon-search
  Visa/dölj filter
= content_tag :div, :id => "purchase_filter" do
  = form_tag purchases_path, method: :get, class: "form form-inline" do
    = field_set_tag("Filter") do
      #purchase_status_filter{style: "display: inline;"}
        = label_tag "Status"
        = filter_select_tag "workflow_state",
                            Purchase.states_collection,
                            "first",
                            "last",
                            placeholder: "Välj status(ar)",
                            include_blank: true,
                            multiple: true

      #purchase_person_filter{style: "display: inline;"}
        = label_tag "Inköpt av"
        = filter_select_tag "person_id",
                            Person.all,
                            "id",
                            "name",
                            placeholder: "Välj en person",
                            include_blank: true

      #purchase_business_unit_filter{style: "display: inline;"}
        = label_tag "Affärsenhet"
        = filter_select_tag "business_unit_id",
                            BusinessUnit.all,
                           "id",
                           "name",
                           placeholder: "Välj affärsenhet(er)",
                           include_blank: true,
                           multiple: true

    = field_set_tag("Inköpsdatum") do
      = filter_date_range_tags :purchased_on

    = field_set_tag("Ändringsdatum") do
      = filter_date_range_tags :updated_at

    = submit_tag "Filtrera", id: "filter_submit", class: "btn btn-primary"

:javascript
  $("#purchase_status_filter .btn").click(function() {
    var element = "#filter_workflow_state_" + $(this).attr("value");
    if($(this).hasClass("active")) {
      $(element).attr("disabled", "disabled");
    } else {
      $(element).removeAttr("disabled");
    }
  });

  $("select").chosen();

  $(".datepicker").datepicker({
    weekStart: 1,
    format: "yyyy-mm-dd"
  });

  $("#purchase_filter_toggle").click(function() {
    if($("#purchase_filter").is(":visible")) {
      $("#purchase_filter").hide();
      $("#purchase_filter_toggle").removeClass("active");
    }
    else {
      $("#purchase_filter").show();
      $("#purchase_filter_toggle").addClass("active");
    }
  });

  $("#purchase_filter").hide();

app/views/purchases/_form.html.haml
= semantic_form_for(@purchase, html: { class: "form-horizontal" }) do |form|
  = form.semantic_errors

  = form.inputs :name => "Beskrivning" do
    - if @purchase.new? && can?(:edit, :purchase_owner)
      = form.input :person, include_blank: false

    = form.input :purchased_on, as: :string
    = form.input :budget_post, collection: option_groups_from_collection_for_select(BusinessUnit.all, :budget_posts, :name, :id, :name, @purchase.budget_post.try(:id))
    = form.input :description

  %fieldset#purchase_items
    %legend Inköpsdelar
    = form.semantic_fields_for :items do |item|
      = render 'item_fields', :f => item
    .links
      = link_to_add_association 'Lägg till inköpsdel', form, :items

  = form.actions do
    = form.action :submit, as: :button, button_html: { class: "btn-primary" }

:javascript
  $(document).ready(function() {
    $("select").chosen();
    $("#purchase_purchased_on").datepicker({
      weekStart: 1,
      format: "yyyy-mm-dd"
    });
  });

app/views/purchases/_history.html.haml
%section.row-fluid#history
  .span12
    %h2 Historik
    %table.table.table-striped
      %thead
        %tr
          %th Status
          %th Tidpunkt
          %th Person
      %tbody
        - purchase.state_history.each do |version|
          %tr
            %td= status version
            %td= l version.version_date, format: :long
            %td= link_to_originator version

app/views/purchases/_info.html.haml
%section.row-fluid
  .span3
    %dl
      %dt Inköpt av
      %dd= link_to purchase.person, purchase.person, title: purchase.person.login
      %dt Inköpt
      %dd= l purchase.purchased_on
      %dt Beskrivning
      %dd= purchase.description
  .span3#budget
    %dl
      %dt Kostnadsställe
      %dd= link_to purchase.business_unit, purchase.business_unit
      %dt Budgetpost
      %dd= link_to purchase.budget_post, purchase.budget_post
      -if can? :manage, BudgetPost
        %dt Budgetstatus
        %dd
          = number_to_currency purchase.budget_row.total
          av
          = number_to_currency purchase.budget_row.sum
  .span8#receipt
    Häfta fast ditt kvitto här!
  %nav.span6.btn-toolbar
    %span.pull-right
      = render :partial => "modify_form", :locals => {:purchase => @purchase}

app/views/purchases/_item_fields.html.haml
.nested-fields.purchase_item
  = f.inputs do
    = f.input :id, as: :hidden
    = f.input :amount
    = f.input :comment
    = f.input :product_type, :collection => ProductType.all, :include_blank => false
    = link_to_remove_association "Ta bort inköpsdel", f

app/views/purchases/_items.html.haml
%section.row-fluid#items
  .span12
    %h2 Inköpsdelar
    %table.table.table-striped
      %thead
        %tr
          %th Kommentar
          %th Produkttyp
          %th Summa
      %tbody
        - purchase.items.each do |item|
          %tr
            %td= item.comment
            %td= item.product_type
            %td= number_to_currency item.amount
      %tfoot
        %tr
          %th
          %th Total
          %th= number_to_currency purchase.total

app/views/purchases/_list.html.haml
%table.table.table-striped
  %thead
    %tr
      %th ID
      %th Beskrivning
      %th Summa (SEK)
      %th Inköpt
      %th Status
  %tbody
    - purchases.each do |purchase|
      %tr
        %td= link_to purchase.slug, purchase
        %td= link_to purchase.description, purchase
        %td= number_to_currency purchase.total
        %td= l purchase.purchased_on
        %td= status purchase

app/views/purchases/_modify_form.html.haml
.btn-group
  %button.btn
    %i.glyphicon.glyphicon-print

- if can?(:edit, purchase)
  .btn-group
    %a{ href: edit_purchase_path(purchase), class: "btn" }
      %i.glyphicon.glyphicon-pencil
      = t('edit')

- if can?(:manage, purchase)
  .btn-group
    - if purchase.editable? && ! purchase.confirmed?
      = link_to t('.confirm'), confirm_purchase_path(purchase), method: :put, confirm: t('are_you_sure'), class: "btn btn-success"
      = link_to t('.cancel'), cancel_purchase_path(purchase), method: :put, confirm: t('are_you_sure'), class: "btn btn-danger"
    - if purchase.keepable?
      = link_to t('.bookkeep'), keep_purchase_path(purchase), :method => :put, :confirm => t('are_you_sure'), class: "btn btn-info"
    - if purchase.payable?
      = link_to t('.pay'), pay_purchase_path(purchase), :method => :put, :confirm => t('are_you_sure'), class: "btn btn-info"

app/views/purchases/confirmed.html.haml
%h1 Bekräftade inköp

= form_tag pay_multiple_purchases_path, :method => :put do
  %table.datatable.table.table-striped
    %thead
      %tr
        %th Person
        %th Kontouppgifter
        %th Summa
        %th

    %tbody
      - @purchases.each do |person, sum|
        %tr{ id: "person-#{person.id}", class: cycle(:odd, :even) }
          %td= link_to person, person
          %td= "%s, %s, %s" % [person.bank_name, person.bank_clearing_number, person.bank_account_number]
          %td= number_to_currency sum
          %td
            = check_box_tag "pay[#{person.id}]"
            = label_tag "pay[#{person.id}]", "Betala"

  = submit_tag "Betala!", class: 'btn btn-primary'

app/views/purchases/edit.html.haml
%section.container-fluid
  .row-fluid
    .span12
      %h1= t '.title'

      %p
        = link_to t('back'), purchases_path
        = link_to t('show'), purchase_path(@purchase)

      = render 'form'

      :javascript
        $(document).ready(function(){
          $("#business_unit").val(#{@purchase.business_unit.id});
          $("#business_unit").trigger('change');
        });

app/views/purchases/index.html.haml
%section.container-fluid
  .row-fluid
    .span12
      %h1 Inköp

      = render "filter_form"

      %table.table.table-striped
        %thead
          %tr
            %th ID
            %th Beskrivning
            %th Köpt av
            %th Inköpt
            %th Status

        %tbody
          - for purchase in @purchases
            %tr
              %td= link_to ("%03d" % purchase.id), purchase
              %td= truncate purchase.description
              %td= link_to purchase.person, purchase.person, title: purchase.person.login
              %td= purchase.purchased_on.to_s(:iso)
              %td= status purchase

      = paginate @purchases

app/views/purchases/new.html.haml
%section.container-fluid
  .row-fluid
    .span12
      %h1 Lägg till inköp
      = render 'form'

app/views/purchases/show.html.haml
= stylesheet_link_tag params[:controller], media: "all"

%header.alert-hero.alert-info
  .container-fluid
    .row-fluid
      .span12
        %h1= "#" + @purchase.slug.upcase
        %p= status @purchase

.container-fluid
  = render :partial => 'info', :locals => {:purchase => @purchase}
  = render :partial => 'items', :locals => {:purchase => @purchase}
  = render :partial => 'history', :locals => {:purchase => @purchase}