config/routes.rb
Cashflow::Application.routes.draw do
  resources :budget_posts

  devise_for :users,
             class_name: "Person",
             controllers: { omniauth_callbacks: "people/omniauth_callbacks" }
  devise_scope :user do
    get "sign_in",
        to: "people/omniauth_callbacks#new",
        as: :new_session
    delete "sign_out",
           to: "people/omniauth_callbacks#destroy",
           as: :destroy_user_session
  end

  localized(["sv"]) do
    resources :product_types
    resources :budget, except: [:destroy] do
      resources :budget_rows, as: "rows", only: [:index, :show, :edit, :update]
    end
    resources :budget_posts
    resources :business_units
    resources :purchases do
      collection do
        get :confirmed
        put :pay_multiple
      end
      member do
        put :confirm
        put :pay
        put :keep
        put :cancel
      end
    end

    resources :people, except: [:destroy] do
      collection do
        get :search
      end
    end

    root to: "dashboard#index"
  end
end

app/models/business_unit.rb
class BusinessUnit < ActiveRecord::Base
  extend FriendlyId
  friendly_id :short_name
  validates_presence_of :name, :short_name, :description
  validates :mage_number, presence: true
  validates :mage_default_series, presence: true

  has_many :budget_posts
  has_many :purchases, through: :budget_posts

  default_scope -> { order('name ASC') }

  def to_s
    name
  end

  def active_text
    active? ? 'Ja' : 'Nej'
  end
end

app/controllers/business_units_controller.rb
class BusinessUnitsController < ApplicationController
  load_and_authorize_resource # :find_by => :short_name
  before_filter :get_items, only: [:show, :edit, :update, :destroy]

  def index
    @business_units = BusinessUnit.all
  end

  def show
  end

  def new
    @business_unit = BusinessUnit.new
  end

  def edit
  end

  def create
    @business_unit = BusinessUnit.new(params[:business_unit])

    if @business_unit.save
      redirect_to(@business_unit,
                  notice: I18n.t("notices.business_unit.success.created"))
    else
      render :new
    end
  end

  def update
    if @business_unit.update_attributes(params[:business_unit])
      redirect_to(@business_unit,
                  notice: I18n.t("notices.business_unit.success.updated"))
    else
      render :edit
    end
  end

  def destroy
    unless @business_unit.destroy
      i18n_path = "activerecord.errors.models.business_unit.cannot_be_removed"
      flash[:error] = I18n.t(i18n_path)
    end

    redirect_to(business_units_url)
  end

  protected

  def get_items
    @items = [{ key: :show_business_unit,
                name: @business_unit.name,
                url: business_unit_path(@business_unit) },
              { key: :edit_business_unit,
                name: I18n.t("edit"),
                url: edit_business_unit_path(@business_unit) }
             ]
  end
end

app/views/business_units/_form.html.haml
= semantic_form_for(@business_unit) do |form|
 = form.inputs :name => "Attribut" do
  = form.input :name
  = form.input :short_name
  = form.input :email
  = form.input :mage_number,
               as: :select,
               collection: Mage::Organ.all.map { |o| [o.name, o.number] }
  = form.input :mage_default_series,
               :as => :select,
               :collection => Mage::Series.all.map { |s| ["#{s.name} (#{s.letter})", s.letter] }
  = form.input :description
  = form.input :active
 = form.actions do
  = form.action :submit, as: :button

app/views/business_units/edit.html.haml
%h1= t '.title'

= render 'form'

app/views/business_units/index.html.haml
%h2= t('.title')

%table.table.table-striped
  %thead
    %tr
      %th Namn
      %th Förkortning
      %th Aktiv
      %th.actions

  %tbody
    - for business_unit in @business_units
      %tr
        %td= link_to business_unit.name, business_unit_path(business_unit)
        %td= business_unit.short_name
        %td= business_unit.active_text
        %td
          = link_to edit_business_unit_path(business_unit), class: 'btn' do
            %i.glyphicon.glyphicon-pencil
            = t('edit')
          = link_to business_unit, confirm: t('are_you_sure'), method: :delete, class: 'btn btn-danger' do
            %i.glyphicon.glyphicon-trash
            = t('destroy')

.well
  = link_to new_business_unit_path, class: 'btn btn-info' do
    %i.glyphicon.glyphicon-file
    Ny affärsenhet

app/views/business_units/new.html.haml
%h1= t '.title'

= render 'form'

app/views/business_units/show.html.haml
%h1= @business_unit

%p
  %strong Aktiv:
  = @business_unit.active_text

%article
  = @business_unit.description

  = render 'purchases/list', purchases: @business_unit.purchases.order("year desc, slug")